### PR TITLE
Update bower.json to include main files & move callbacks to scope.

### PR DESCRIPTION
**Pull request by glaidler**
Added main so that bower-concat and other grunt tools can do their job.

### CODE REVIEW

**Comment by glaidler** [comment]
Also moved the callbacks to the scope - as per commit comment.  I always do callback binding this way, so please let me know if this won't work in some scenarios.

**Comment by yaru22** [comment]
Thanks for your contribution @glaidler.

Could you make the source code changes to `src/angular-hovercard.js` instead of `dist/angular-hovercard.js`? Files under `dist/` is auto-generated by Grunt task (you can do `npm install && bower install && grunt` to re-generate `dist/*` and `demo/*`).

Thanks.

**Comment by glaidler** [comment]
sorry - my bad.  Have done this.

**Comment by yaru22** [comment]
Sorry about the late reply @glaidler. I just remembered that we tried to get rid of isolate scope. You can see that commit https://github.com/yaru22/angular-hovercard/commit/6816e55ac1e07270f3efc3d9a125465728081fb3.

So the following code:
```
$scope.onHoverIn = $scope.$eval($attrs.onHoverIn);
$scope.onHoverOut = $scope.$eval($attrs.onHoverOut);
```
was intentional.

I'll gladly accept the change in `bower.json` but could you revert the other changes back?

Thanks!

**Comment by glaidler** [comment]
I have reverted as requested - sorry for confusion!

**Comment by yaru22** [comment]
No problem at all! Thanks for your contribution @glaidler.

**Pull request merged**
